-- ==============================================================================
-- 🧾 ACADEMY STUDENT PORTAL - SUPABASE DATABASE & STORAGE SCHEMA
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/_/sql
-- ==============================================================================

-- 1. Create payment_verifications table
CREATE TABLE IF NOT EXISTS public.payment_verifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  email TEXT NOT NULL,
  discord_id TEXT,
  discord_username TEXT,
  is_discord_verified BOOLEAN DEFAULT false,
  plan_name TEXT NOT NULL,
  tier_number INTEGER DEFAULT 1,
  amount NUMERIC NOT NULL,
  currency TEXT DEFAULT 'NPR',
  payment_method TEXT NOT NULL,
  transaction_id TEXT NOT NULL,
  proof_url TEXT,
  notes TEXT,
  status TEXT DEFAULT 'pending', -- 'pending', 'verified', 'rejected'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::TEXT, now()) NOT NULL
);

-- Index for fast lookup by Discord ID
CREATE INDEX IF NOT EXISTS idx_payment_verifications_discord_id ON public.payment_verifications(discord_id);
CREATE INDEX IF NOT EXISTS idx_payment_verifications_transaction_id ON public.payment_verifications(transaction_id);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.payment_verifications ENABLE ROW LEVEL SECURITY;

-- Allow students to submit payment proofs
DROP POLICY IF EXISTS "Allow public insert verifications" ON public.payment_verifications;
CREATE POLICY "Allow public insert verifications"
  ON public.payment_verifications
  FOR INSERT
  WITH CHECK (true);

-- Allow reading records
DROP POLICY IF EXISTS "Allow public read verifications" ON public.payment_verifications;
CREATE POLICY "Allow public read verifications"
  ON public.payment_verifications
  FOR SELECT
  USING (true);

-- 3. Create Supabase Storage Bucket for Screenshot Proofs ('payment-proofs')
INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-proofs', 'payment-proofs', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Storage RLS Policies
DROP POLICY IF EXISTS "Allow public uploads to payment-proofs" ON storage.objects;
CREATE POLICY "Allow public uploads to payment-proofs"
  ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'payment-proofs');

DROP POLICY IF EXISTS "Allow public access to payment-proofs" ON storage.objects;
CREATE POLICY "Allow public access to payment-proofs"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'payment-proofs');
